[package]
name = "e09_uretprobe-ebpf"
version = "0.1.0"
edition = "2021"

[dependencies]
e09_uretprobe-common = { path = "../e09_uretprobe-common" }

aya-ebpf = { workspace = true }
aya-log-ebpf = { workspace = true }

[build-dependencies]
which = { workspace = true }

[[bin]]
name = "e09_uretprobe"
path = "src/main.rs"
