[package]
name = "e19_sk_msg-ebpf"
version = "0.1.0"
edition = "2021"

[dependencies]
e19_sk_msg-common = { path = "../e19_sk_msg-common" }

aya-ebpf = { workspace = true }
aya-log-ebpf = { workspace = true }

[build-dependencies]
which = { workspace = true }

[[bin]]
name = "e19_sk_msg"
path = "src/main.rs"
