[package]
name = "e01_tracepoint-ebpf"
version = "0.1.0"
edition.workspace = true

[dependencies]
e01_tracepoint-common = { path = "../e01_tracepoint-common" }

aya-ebpf = { workspace = true }
aya-log-ebpf = { workspace = true }

[build-dependencies]
which = { workspace = true }

[[bin]]
name = "e01_tracepoint"
path = "src/main.rs"
