[package]
name = "e15_cgroup_skb-ebpf"
version = "0.1.0"
edition = "2021"

[dependencies]
e15_cgroup_skb-common = { path = "../e15_cgroup_skb-common" }

aya-ebpf = { workspace = true }
aya-log-ebpf = { workspace = true }

[build-dependencies]
which = { workspace = true }

[[bin]]
name = "e15_cgroup_skb"
path = "src/main.rs"
