[package]
name = "e16_cgroup_sockopt-ebpf"
version = "0.1.0"
edition = "2021"

[dependencies]
e16_cgroup_sockopt-common = { path = "../e16_cgroup_sockopt-common" }

aya-ebpf = { workspace = true }
aya-log-ebpf = { workspace = true }

[build-dependencies]
which = { workspace = true }

[[bin]]
name = "e16_cgroup_sockopt"
path = "src/main.rs"
