[package]
name = "e20_sock_ops-ebpf"
version = "0.1.0"
edition = "2021"

[dependencies]
e20_sock_ops-common = { path = "../e20_sock_ops-common" }

aya-ebpf = { workspace = true }
aya-log-ebpf = { workspace = true }

[build-dependencies]
which = { workspace = true }

[[bin]]
name = "e20_sock_ops"
path = "src/main.rs"
