[package]
name = "e08_uprobe-ebpf"
version = "0.1.0"
edition = "2021"

[dependencies]
e08_uprobe-common = { path = "../e08_uprobe-common" }

aya-ebpf = { workspace = true }
aya-log-ebpf = { workspace = true }

[build-dependencies]
which = { workspace = true }

[[bin]]
name = "e08_uprobe"
path = "src/main.rs"
